### ISSUE TITLE
Add option to RunTest to break into debugger on error/rte/etc.

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#10]

**Comment by MathiasAugstein** [comment]
Proposal: 
Add another parameter debugMode which takes strings as input:
- "off": disable debugger (default)
- "on": enable debugger
- "debug on error": enable debugger and debug-on-error-option
- "svar nvar wave": enagle debugger and NVAR-SVAR-WAVE-Checking
- "all": enable with both options

Internally use a switch-case-statement with regular expressions, to be case-insensitive and allow for underscores instead of whitespaces. Additionally create output to console if the given option is not recognized.

Keep the allowDebug option for compatibility, but treat allowDebug=1 internally as debugMode="on".

**Comment by MichaelHuth** [comment]
ok, but change debugMode to bit based setting, where
bit 0 - debug on error
bit 1 - svar nvar wave checking

which means 
0 = both options off
1 = debug on error
2 = svar nvar wave checking
3 = both options on

if one option is enabled then Debugger is also enabled.

**Comment by MathiasAugstein** [comment]
And allowDebug = 1 is equal to "keep", allowDebug = 0 is equal to "off"

**Comment by MichaelHuth** [comment]
Note that the change should also include that the debugger should open when an assertion fails, so one can review the stack trace and state of the test case.

So another bit/constant for this setting is required.
