### ISSUE TITLE
UTF_TD_GENERATOR functions are called way too often

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#168]
```igorpro
#include "unit-testing"

Function/WAVE Gen()

	print "called"
	
	Make/FREE/N=1 data
	return data
End

// UTF_TD_GENERATOR Gen
Function Test([variable var])

	PASS()
End
```

```
•runTest("procedure")
  called
  called
  Start of test "Unnamed"
  called
  called
  Entering test suite "Procedure"
  called
  Entering test case "Test:0"
  called
  Leaving test case "Test:0"
  Finished with no errors
  Leaving test suite "Procedure"
  Test finished with no errors
  End of test "Unnamed"
```

Change that, so that it is only called once and add CI tests to verify and keep it like that.

**Comment by MichaelHuth** [comment]
In getTestCasesMatch the function CheckFunctionSignaturesTC is called (which calls the DataGenerator) and afterwards GetTestCaseCount (which also calls the DataGenerator). These information could be gathered combined, by e.g. returning two lists.

Also in CheckFunctionSignaturesTC the fullTestCase can be added to the output list, such that building the list in getTestCasesMatch can be removed.

**Comment by MichaelHuth** [comment]
Latest approach idea:

In the beginning build text wave in getTestCasesMatchwith all relevant information for test cases.

Example fields:
procWin0 testcase0 fullFunctionName list_of_datagenerators list_of_dgen_wavesizes skip? expected_fail
procWin0 testcase1 fullFunctionName list_of_datagenerators list_of_dgen_wavesizes

Additionally build data generator name to returned wave mappig wave (wave ref wave where dimLabels are dgen Names)
dgenName:WaveRef -> returned wave

Determine if function sig fits to multimultidata testcase ,in begin of CallTestCase for this specific funcsig, add if branch

In main loop instead of running over procWin and funcNames, run only over index of above text wave that contains one row per testcase.

Goal:
Parsing of function header only once.
Calling of multidata generators only once.

Current concept start:
Add creation of above text wave in current code transparently.
then
Replace locations where information is currently parsed/gathered to look it up in our new wave.
