### ISSUE TITLE
Enhance difference printing for equal waves

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#221]
- Output the name for free waves if present. Since IP9 free waves can have names via
```
Function Dostuff()
	Make/FREE=1 important_name
	print NameOfWave(important_name)
End
```
- Drop unused trailing `[0]` dimensions in difference table
- Comparing the output of text wave with differing strings can be hard. Maybe we can provide a colorized diff of the string as well?
- Can we remove trailing zeros for integers in
```
Dimensions  |Labels|Value    |
------------|------|---------|
[3][0][0][0]|      |15.000000|
            |      |17.000000|
```
- Can we also display enough digits so that the there is always a difference visible?

**Comment by t-b** [comment]
Last point: print number to string with increasing digit number until diff is present

**Comment by Garados007** [comment]
The first bullet point is already done in the current release. If I use the following code:

```igorpro
static Function TestWave()
	Make/FREE=1 wv1 = { 15 }
	Make/FREE=1 wv2 = { 17 }
	CHECK_EQUAL_WAVES(wv1, wv2)
End
```

I get the following result:
```
  Assuming equality using mode WAVE_DATA for waves wv1 and wv2; detailed: Waves difference:
Wave1: 0x0851d19340
Wave2: 0x0851d194c0
Dimensions  |Labels|Value    |
------------|------|---------|
[0][0][0][0]|      |15.000000|
            |      |17.000000|
: is false. Assertion "CHECK_EQUAL_WAVES(wv1, wv2)" failed in line 10, procedure "Proc0"
```

The names `wv1` and `wv2` are already included in the output.

**Comment by t-b** [comment]
Good find that NameOfWave already helps us here.

**Comment by t-b** [comment]
@Garados007 On second thought. Can we have the free wave names in

```
Wave1: 0x082651f8b0
Wave2: 0x082651f2d0
```

instead of the memory addresses if these are available?

**Comment by Garados007** [comment]
I think we can have both. Something like this:
`Wave1: wv1 (0x082651f8b0)`
I don't know if the memory address is somewhere needed but this solution will still keep it.

**Comment by t-b** [comment]
@Garados007 Fine with me.

**Comment by Garados007** [comment]
I am trying to solve the trimming of trailing zeros of the numbers. There is a format specifier `%g` that will do this automatically. The current used `%f` will always keep six digits after the decimal point.

This will look like this:
```igorpro
static Function TestWave()
	Make/FREE=1 wv1 = { 15, 0.003401, 1e-10 }
	Make/FREE=1 wv_2 = { 17, 0.003, 1234567890 }
	CHECK_EQUAL_WAVES(wv1, wv_2)
End
```

Output:
```
Dimensions|Labels|Value      |
----------|------|-----------|
[0]       |      |15         |
          |      |17         |
[1]       |      |0.003401   |
          |      |0.003      |
[2]       |      |1e-10      |
          |      |1.23457e+09|
```

(this example contains the change in ddd0261)

**Comment by Garados007** [comment]
Another option will be to use the output of `%f` and trim the characters by "hand" (code).

**Comment by MichaelHuth** [comment]
The solution with %g looks inconvenient for comparing the numbers for case 2 as the exponent is not the same.

I think for output with the same exponent %g has no option. So the way would be to go with %f and trim trailing zeroes.
The floating point values have a certain precision depending on type that translates for decimal representation in a certain number of digits.  Thus, if you enforce too many digits to be converted to a string the last digits will be non-zero for all not exactly representable numbers, e.g.:
```
printf "%.20f\r", 1.55
1.55000000000000004441
```
Double precision numbers use 53 bits for the mantisse, thus in decimal you get `53 * log(2) = 15.955` digits.
So with `trunc(log(n))` you get the digits in front of the dot and 15.955 minus that value give you the digits after the dot.
For double precision I would expect something like that to work:
```
val = floor(15.955 - trunc(log(n)))
val = val <= 0 ? 0 : val
format = "%." + num2istr(val) + "f"
sprintf str, format, n

```
and then cut the zeroes at the end.

Does that make sense?

**Comment by Garados007** [comment]
Yes. I could change the code so it will produce this:
```
Dimensions|Labels|Value                     |
----------|------|--------------------------|
[0]       |      |15                        |
          |      |17                        |
[1]       |      |0.00340100005269051       |
          |      |0.00300000002607703       |
[2]       |      |0.000000000100000001335143|
          |      |1234567936                |
```

There are some nasty stuff at the end but this has something to do with the internal representation of the numbers.

For a future issue it could be nice to align these numbers at their decimal point.

**Comment by Garados007** [comment]
With 249d783 it will show all digits of the full number and only trim some insignificant zeros at the end of the number. So it will be possible to view the whole number including the difference. This will solve the bullet point 5.

Bullet point 6 is a little bit trickier because I have to check for the start of the difference and have to reduce the number of shown digits. With the current solution you only have something around 16 digits and I think this is enough to see.

**Comment by Garados007** [comment]
Colorized diffs are impossible with the current version of Igor Pro. I cannot color the output to the history. I didn't found any references in the docs and I tried many stuff but nothing worked (html, markdown, rtf, label formatting). There is an old [forum post](https://www.wavemetrics.com/forum/igor-pro-wish-list/allow-users-add-color-history-text) with this issue but since then no update.

**Comment by MichaelHuth** [comment]
I think the issue here is the following:

In your test case you create waves of the type single precision float32. 
You put these as argument in GetNiceStringForNumber where it is implicitly converted to double.
The bit count for float32 mantisse is 23, while you use currently 53 for double for all inputs.

If you replace the 15.955 depending on the input floating point type with either
53 * log(2) or 23 * log(2) then the latter would give you about 6.9 digits. With that you would not get the "nasty stuff" as you describe it.

**Comment by Garados007** [comment]
Oh yes. I forgot the thing about float and double. I will try to look at it tomorrow. Maybe I can get more nice results.

**Comment by t-b** [comment]
> Colorized diffs are impossible with the current version of Igor Pro. I cannot color the output to the history. I didn't found any references in the docs and I tried many stuff but nothing worked (html, markdown, rtf, label formatting). There is an old [forum post](https://www.wavemetrics.com/forum/igor-pro-wish-list/allow-users-add-color-history-text) with this issue but since then no update.

Good point. I forgot about that forum post. And I was the OP ...
