### ISSUE TITLE
Check if the general group in CHECK_WAVE flags documentation really makes sense

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#37]
See https://docs.byte-physics.de/igor-unit-testing-framework/flags.html#general.
IIRC NULL_WAVE is only accepted for the major type.

**Comment by MichaelHuth** [comment]
@t-b 
The current implementation accepts NULL_WAVE for majorType and for minorType.
If a minorType is given it is always checked after majorType. Thus the minorType check also needs to have a constant for a null wave. That is why NULL_WAVE appears in "General".

Though from the logic we should clear that up, because a call where against a null wave is checked through major and minor type does not make much sense.
